### ISSUE TITLE
Embeding Not Working

### ISSUE THREAD

**Issue by zlassiter** [bradthomas127/gitpress-repo#1]
currently using Wordpress 3.5.1 and the shortcode appears to no longer function....

using

[repo name="Datastore" author="KzooHack"]

**Comment by bradthomas127** [comment]
Not to sure why it's not working for you the Demo it works and i am also on 3.5.1
http://wp-ultra.com/2012/07/gitpress-repo-plugin/

The shortcode with branch has not worked for awhile now but i don't think it's a WordPress issue, think it from a github api change.
